#!/usr/bin/env Rscript

# code/get_downloads_url.R
#
# THIS CODE WEAS FULLY GENERATED BY CLAUDE CODE FREE VERSION
#
# Extrae nombre de archivo, URL de descarga y fecha de cargue desde las
# páginas de listados de TMSA y guarda dos CSVs en data/.
#
# IMPORTANTE: este script asume que se ejecuta desde la raíz del repositorio,
# p.ej.: Rscript code/get_downloads_url.R

suppressPackageStartupMessages({
  library(rvest)
})

FUENTES <- list(
  list(
    url    = "https://storage.googleapis.com/validaciones_tmsa/ValidacionTroncal.html",
    output = file.path("data", "download url validaciones.csv")
  ),
  list(
    url    = "https://storage.googleapis.com/validaciones_tmsa/Salidas.html",
    output = file.path("data", "download url salidas.csv")
  )
)

extraer_tabla_archivos <- function(pagina, url_origen) {
  tablas <- pagina |> html_elements("table")

  if (length(tablas) == 0) {
    message("ERROR: no se encontró ninguna tabla en ", url_origen)
    return(NULL)
  }

  tabla_objetivo <- NULL
  for (t in tablas) {
    encabezados <- t |> html_elements("th") |> html_text(trim = TRUE)
    if ("Nombre Archivo" %in% encabezados) {
      tabla_objetivo <- t
      break
    }
  }

  if (is.null(tabla_objetivo)) {
    message("ERROR: ninguna tabla en ", url_origen,
            " tiene el encabezado 'Nombre Archivo'.")
    return(NULL)
  }

  filas_links <- tabla_objetivo |> html_elements("tr td:first-child a")

  if (length(filas_links) == 0) {
    message("ERROR: no se encontraron enlaces de descarga en la tabla de ", url_origen)
    return(NULL)
  }

  nombres <- filas_links |> html_text(trim = TRUE)
  urls    <- filas_links |> html_attr("href")

  fechas <- tabla_objetivo |>
    html_elements("tr") |>
    Filter(f = function(fila) length(html_elements(fila, "td")) >= 3) |>
    sapply(function(fila) {
      celdas <- html_elements(fila, "td")
      html_text(celdas[[3]], trim = TRUE)
    })

  if (length(fechas) != length(nombres)) {
    message("ERROR: desalineación entre nombres (", length(nombres),
            ") y fechas (", length(fechas), ") en ", url_origen)
    return(NULL)
  }

  data.frame(
    nombre_archivo = nombres,
    url_descarga    = urls,
    fecha_cargue    = fechas,
    stringsAsFactors = FALSE
  )
}

procesar_fuente <- function(fuente) {
  message("Procesando: ", fuente$url)

  pagina <- tryCatch(
    read_html(fuente$url),
    error = function(e) {
      message("ERROR al descargar ", fuente$url, ": ", conditionMessage(e))
      return(NULL)
    }
  )

  if (is.null(pagina)) return(FALSE)

  resultado <- extraer_tabla_archivos(pagina, fuente$url)
  if (is.null(resultado) || nrow(resultado) == 0) {
    message("ERROR: resultado vacío para ", fuente$url, ", no se escribe el CSV.")
    return(FALSE)
  }

  n_na <- sum(is.na(resultado$url_descarga))
  if (n_na > 0) {
    message("Aviso: ", n_na, " fila(s) sin URL de descarga (NA) en ", fuente$url)
  }

  dir.create(dirname(fuente$output), recursive = TRUE, showWarnings = FALSE)
  write.csv(resultado, fuente$output, row.names = FALSE)

  message("OK: ", nrow(resultado), " filas escritas en ", fuente$output)
  return(TRUE)
}

main <- function() {
  resultados <- vapply(FUENTES, procesar_fuente, logical(1))

  if (!all(resultados)) {
    message("Una o más fuentes fallaron.")
    quit(status = 1)
  }

  message("Todas las fuentes procesadas correctamente.")
}

main()
